name: Conditional CI Pipeline

# Trigger the workflow on push to the 'development' branch.
on:
  push:
    branches:
      - dev

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest scikit-learn flake8
    
    # Linting with flake8
    - name: Get modified files
      id: modified_files
      run: |
        git fetch origin ${{ github.event.before }} --depth=1
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > modified_files.txt
        cat modified_files.txt

    - name: Lint code with flake8
      if: contains(steps.modified_files.outputs.modified_files, '.py')
      run: flake8 .

    # Running tests with pytest
    - name: Run tests with pytest
      if: contains(steps.modified_files.outputs.modified_files, 'test_')
      run: pytest
